- client/index.css
- client/index.js
- client/public/index.html
- client/public/index.js
- package-lock.json
- package.json
- webpack.config.js
babel, css-loader, style-loader 설정
> [Add] webpack 설정

- client/components/Column/column.css
- client/components/Column/index.js
- client/components/Modal/index.js
- client/components/Modal/modal.css
- client/components/Note/index.js
- client/components/Todo/index.js
- client/components/index.js
- client/index.js
> [Modify] 모달 컴포넌트

- .eslintrc
- client/components/Modal/Sections/col-modal.js
- client/components/Modal/Sections/note-modal.js
- client/components/Modal/modal.css
- client/components/Note/note.js
- client/components/Todo/todo.js
> [Modify] column과 note 모달 컴포넌트  분리

- client/components/Modal/Sections/col-modal.js
- client/components/Modal/Sections/note-modal.js
- client/components/Modal/modal.js
- client/components/Note/note.js
> [Modify] 모달창 상속

- client/components/Column/column.js
- client/components/Note/Sections/note-form.js
- client/components/Note/note.css
- client/components/Note/note.js
- client/components/Todo/todo.js
- client/components/component.js
- client/index.js
- dist/index.html
- Component에 공용함수와 jsdoc 주석 추가
- 모든 Props를 사용하는 컴포넌트의 props 항목에 대해 jsdoc 추가
- Todo에 GhostNote를 추가
> [Add] 초기화면에 더미 데이터 추가 및 드래그 구현

- client/components/Modal/Sections/col-modal.js
- client/components/Modal/Sections/note-modal.js
- client/components/Modal/modal.js
- client/components/Note/Sections/note-form.js
- client/components/Note/note.js
> [Add] 노트 변경 구현

- client/components/Column/column.css
- client/components/Column/column.js
- client/components/Note/Sections/fake-note.js
- client/components/Note/Sections/ghost-note.js
- client/components/Note/note.css
- client/components/Note/note.js
- client/components/Todo/todo.js
- client/components/component.js
- client/global.css
- client/index.js
- package-lock.json
- GhostNote, FakeNote 클래스 추가
- Note의 disguise(note) 함수 추가
- Component의 isHigherThan(component) 구현 및 getComponentIndex() 함수 구현
- 아직 제일 밑의 칸으로는 이동이 안됨
> [Feature] 드롭 구현

- client/components/Column/column.css
- client/components/Column/column.js
- client/components/Note/Sections/fake-note.js
- client/components/Note/Sections/ghost-note.js
- client/components/Note/note.css
- client/components/Todo/todo.js
- client/global.css
- 사용하지 않는 unmount()함수 제거
- 제목 더블 클릭시 커럼 제목 수정
- colEditBtn 삭제
- 모든 Element에서 드래그 발생하지 않도록 변경
This closes #36 
This closes #35
> [Modify] Note 끌기시 기준위치 유지시키기

- .vscode/settings.json
- client/api/index.js
- client/index.js
- package-lock.json
- server/controllers/columns.js
- server/controllers/helper.js
- server/controllers/todos.js
- server/models/columns.js
- server/queries.js
- server/routes/api.js
- server/routes/columns.js
- server/routes/todos.js
- server/services/columns.js
- server/services/index.js
테스트는 프론트앤드와 연동하면서 차근차근 진행해도 될 것 같습니다.
> 백앤드 컬럼 관련 내용 초기화

- .eslintrc
- client/api/index.js
- client/index.js
- server/models/notes.js
- server/queries.js
- server/services/columns.js
- 초기 노트 정보들도 가져오도록 수정
- eslintrc 수정
> initTodo() 초기화

- client/api/index.js
- client/components/Column/Sections/columnAddBtn.js
- client/components/Column/column.css
- client/components/Column/column.js
- client/global.css
- client/index.js
- server/controllers/columns.js
- server/models/columns.js
- server/queries.js
- server/routes/api.js
- server/services/columns.js
- column 추가 버튼 클릭시 column이 버튼 앞에 생성
- column css 수정
> [Fix] column이 추가될 때 추가 버튼 앞에 생성

- client/api/index.js
- client/components/Column/column.js
- client/components/Note/Sections/note-form.js
- client/components/Note/note.js
- client/components/index.js
- client/index.js
- server/controllers/notes.js
- server/models/notes.js
- server/queries.js
- server/routes/api.js
- server/routes/notes.js
- server/services/notes.js
- webpack.config.js
> [Add] Note 추가, 불러오기 구현

- client/components/Column/column.css
- client/components/Column/column.js
- client/components/Todo/todo.css
- server/routes/api.js
> Front-end 칼럼 삭제 기능 구현

- client/api/index.js
- client/components/Column/column.js
- client/index.js
> 백엔드 칼럼 삭제 기능 구현

- client/api/index.js
- client/components/Column/column.js
- client/components/Modal/Sections/note-modal.js
- client/components/Note/Sections/note-form.js
- server/controllers/notes.js
- server/services/notes.js
- 노트 삭제시 나머지 position이 밀리도록 구현
> 노트 수정 및 삭제 구현

- client/api/index.js
- client/components/Modal/Sections/col-modal.js
> Column 제목 수정

- client/global.css
- root div의 position을 absolute로 변경
> Column 여러개 추가시 헤더가 꽉 차지 않는 문제 해결

- client/components/Note/Sections/note-form.js
> 노트폼 버튼 기능 수정

- client/components/Header/header.js
- client/components/Log/log.css
- client/components/Log/log.js
- client/components/index.js
- client/index.js
> Log 컴포넌트 생성

- client/global.css
> 헤더 꽉차지 않는 문제해결

- client/components/Header/header.css
- client/components/Todo/todo.css
- client/global.css
- root postion 지움.
- 헤더 position fixed
- todo에 margin-top 줌
> 헤더 길이 문제 해결

- client/api/index.js
- client/components/Column/column.js
- client/components/Modal/Sections/col-modal.js
- client/components/Modal/Sections/confirm-modal.js
- client/components/Note/note.js
- client/event-controller/index.js
- client/event-controller/mock-element.js
- server/services/columns.js
컬럼 드래그 앤 드랍 구현 및 백앤드 연동 완료
이유 모를 버그가 계속 발생해 코드 정리가 필요함.
> Feature/column Dragndrop

- client/components/Column/column.css
- client/components/Header/header.css
- client/components/Menu/Sections/log.js
- client/components/Menu/menu.css
- client/components/Note/note.css
- client/components/Todo/todo.css
- client/event-controller/index.js
- client/event-controller/mock-element.js
- client/global.css
- 타임 스탬프 파싱 추가
- 드래그앤 드랍 에러 방지 처리 추가
- 드래그앤 드랍 잡고 있는 부분을 끌 수 있도록 변경
> 타임 스탬프 파싱 추가

- server/controllers/columns.js
> [Add]  칼럼 무브 로그 작성

- client/components/Column/column.css
- client/components/Modal/Sections/confirm-modal.js
- client/components/Modal/modal.css
> [Modify] confirm 모달 css 수정

- client/components/Note/note.css
- client/components/Note/note.js
- client/event-controller/index.js
- 드래그를 시작하는 순간 바로 스티커가 붙도록 수정
- 컬럼, 노트가 드래그 될 때 각각의 너비 조정
> [Add] 컬럼 드래그 조건 수정

- client/public/index.html
- server/controllers/notes.js
> [Fix] Note 클릭시에도 로그 쌓이는거 수정

- client/components/Column/column.css
- client/components/Header/header.css
- client/components/Menu/menu.css
- client/components/Modal/Sections/col-modal.js
- client/components/Modal/Sections/note-modal.js
- client/components/Modal/modal.css
- client/components/Modal/modal.js
- client/components/Note/note.css
- client/event-controller/index.js
- 수정과 삭제가 안되는 버그 해결
- 스크롤 시에도 제대로 잡게 수정
- 디자인 수정
- 메뉴 애니메이션 수정
> [Fix] 전체 css 정리 및 컬럼 버그 수정
